name: Update Stats

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Fetch feeds and rebuild stats
        run: python3 scripts/update_stats.py

      - name: Commit changes
        id: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/raw data/processed docs/data
          if git diff --cached --quiet; then
            echo "changes=false" >> "$GITHUB_OUTPUT"
          else
            git commit -m "chore: refresh stats"
            echo "changes=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Push changes
        if: ${{ steps.commit.outputs.changes == 'true' }}
        run: git push
